WayWealth/Controllers/SignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.ApplicationServices;
using System.Web.Mvc;
using AutoMapper;
using W2W.ModelKBT.Entities;
using WayWealth.Infrastructure.Auth;
using WayWealth.ViewModels.Sign;
using Recaptcha.Web;
using Recaptcha.Web.Mvc;
using System.Text;
using Common.Web;
using WayWealth.Helpers;
using System.Configuration;
using JWT;
using System.Text.RegularExpressions;
using Google.Authenticator;

namespace WayWealth.Controllers
{
    public class SignController : BaseController
    {
        [HttpGet]
        public ActionResult In(string returnUrl)
        {
            if (User != null)
                return Redirect(Url.Action("index", "home", new { area = "lk" }));

            return View();
        }

        [HttpGet]
        public ActionResult TwoFactorAuthenticate()
        {
            if (User != null)
                return Redirect(Url.Action("index", "home", new { area = "lk" }));

            if (Session["GoogleAuthSuccessPartnerId"] == null)
                return RedirectToAction("in", "sign");

            uint id_user = (uint) Session["GoogleAuthSuccessPartnerId"];
            var retUser = DataService.GetPartner(id_user);
            if (retUser == null || !(retUser.GoogleAuthEnabled ?? false))
                return RedirectToAction("in", "sign");

            return View();
        }

        [HttpPost]
        public ActionResult TwoFactorAuthenticate(TwoFactorAuthenticateView model, string returnUrl)
        {
            if (User != null)
                return Redirect(Url.Action("index", "home", new { area = "lk" }));

            if (Session["GoogleAuthSuccessPartnerId"] == null)
                return RedirectToAction("in", "sign");

            uint id_user = (uint)Session["GoogleAuthSuccessPartnerId"];
            
            var retUser = DataService.GetPartner(id_user);
            if (retUser == null || !(retUser.GoogleAuthEnabled ?? false))
                return RedirectToAction("in", "sign");

            bool IsPersistent = (bool)Session["GoogleAuthIsPersistent"];

            TwoFactorAuthenticator TwoFacAuth = new TwoFactorAuthenticator();
            bool isValid = TwoFacAuth.ValidateTwoFactorPIN(retUser.GoogleAuthKey, model.CodeDigit);

            if (ModelState.IsValid)
            {
                    try
                    {
                    if (isValid && AuthenticationService.LoginFrom2Auth(retUser, IsPersistent))
                        {
                        Session["GoogleIsValidTwoFactorAuthentication"] = true;
                        Session.Remove("GoogleAuthSuccessPartnerId");
                        Session.Remove("GoogleAuthIsPersistent");

                        return Redirect(returnUrl ?? Url.Action("index", "home", new { area = "lk" }));
                    } else
                        {
                        throw new Exception(Resources.Resource.GoogleAuthIncorrectCode);
                        }
                    }
                    catch (Exception exc)
                    {
                        ModelState.AddModelError(string.Empty, exc.Message);
                    }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult In(InView model, string returnUrl)
        {
            if (User != null)
                return Redirect(Url.Action("index", "home", new { area = "lk" }));

            if (!CheckCaptcha())
                return View(model);

            if (ModelState.IsValid)
            {
                try
                {
                    var retUser = AuthenticationService.CheckLogin(model.Login, model.Password);

                    if (retUser != null)
                    {
                        
                        if ((retUser.GoogleAuthEnabled ?? false) && (Session["GoogleIsValidTwoFactorAuthentication"] == null || !(bool)Session["GoogleIsValidTwoFactorAuthentication"]) )
                        {
                            Session["GoogleAuthSuccessPartnerId"] = retUser.id_object;
                            Session["GoogleAuthIsPersistent"] = model.IsPersistent;
                            return RedirectToAction("TwoFactorAuthenticate", "sign");
                        }
                        
                        AuthenticationService.Login(model.Login, model.Password, model.IsPersistent);

                        return Redirect(returnUrl ?? Url.Action("index", "home", new { area = "lk" }));


                    }
                    else
                    {
                        throw new Exception(Resources.Resource.ErrWrongLoginOrPassword);
                    }
                }
                catch (Exception exc)
                {
                    ModelState.AddModelError(string.Empty, exc.Message);
                }
            }

            return View(model);
        }


        [HttpGet]
        public ActionResult Up(string inviter)
        {
            TempData["isLogin"] = false;
            // Если не указан в ссылке Inviter тогда пробуем найти его в куки
            if (string.IsNullOrWhiteSpace(inviter))
            {
                if (this.User != null)
                {
                    inviter = this.User.PersonalId.ToString();
                    TempData["isLogin"] = true;
                }
                else
                {
                    var cookie = Request.Cookies["Inviter"];
                    if (cookie != null)
                        inviter = cookie.Value;
                }
            }

            // Если Inviter Обнаружен
            if (!string.IsNullOrWhiteSpace(inviter))
            {
                var inv = this.DataService.GetPartner(inviter);
                if (inv == null)
                    inviter = null;
                else
                {
                    TempData["inviterName"] = inv.ObjectName;
                    var cookie = new HttpCookie("Inviter");
                    cookie.Value = inviter;
                    cookie.Expires = DateTime.Now.AddYears(1);
                    Response.Cookies.Add(cookie);
                }
            }
            TempData["inviter"] = inviter;


            return View();
        }
        [HttpPost]
        public ActionResult Up(UpView model, string inviter)
        {

            if (!CheckCaptcha())
                return View(model);

            if (ModelState.IsValid)
            {
                try
                {
                    if (model.Password != model.ConfirmPassword)
                        throw new Exception(Resources.Resource.ErrPasswordsDoNotMatch);

                    if (this.DataService.GetPartnerByEmail(model.Email) != null)
                        throw new Exception(Resources.Resource.ErrEmailIsAlreadyRegistred);

                    if (!string.IsNullOrWhiteSpace(model.Login) &&
                        this.DataService.GetPartner(model.Login.Trim()) != null)
                        throw new Exception(Resources.Resource.ErrLoginIsAlreadyRegistred);

                    uint inviterId = 0;
                    if (!string.IsNullOrWhiteSpace(inviter))
                    {
                        model.InviterTxt = inviter;
                    }

                    if (!string.IsNullOrWhiteSpace(model.InviterTxt))
                    {
                        var inv = this.DataService.GetPartner(model.InviterTxt);
                        if (inv == null)
                            throw new Exception(Resources.Resource.ErrInviterNotFound);
                        inviterId = inv.id_object;
                    }

                    var login = model.Login;
                    //if (string.IsNullOrWhiteSpace(login))
                    //    login = model.Email;

                   uint id_client = DataService.CreatePartner(
                        inviterId: inviterId,
                        firstName: model.FirstName,
                        lastName: model.LastName,
                        middleName: model.MiddleName,
                        email: model.Email,
                        password: model.Password,
                        login: login);


                    var partner = this.DataService.GetPartner(id_client);

                    // формирование ссылки
                    string link = CreateUrl2(model.Email);

                    this.MailService.SendMessage(
                      to: model.Email,
                      subject: Resources.Resource.SignUpText,
                      body: string.Format(Resources.Resource.LetterSignUp, 
                      link, 
                      link, 
                      model.Login,
                      $"{model.FirstName} {model.MiddleName} {model.LastName}",
                      model.Password,
                      model.InviterTxt));

                    //email message 
                    //StringBuilder message = new StringBuilder();
                    //var culture = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
                    //if (culture == "ru-RU")
                    //{
                    //    message.Append("<h3>Здравствуйте!</h3>");
                    //    message.Append($"<p>Для завершения регистрации перейдите по ссылке <a href=\"{link}\">{link}</a></p>");
                    //    message.Append("<p>Ссылка действительна в течении 24 часов.</p>");
                    //}
                    //else
                    //{
                    //    message.Append("<h3>Hello!</h3>");
                    //    message.Append($"<p>To complete the registration, click on the link <a href=\"{link}\">{link}</a></p>");
                    //    message.Append("<p>The link is valid for 24 hours..</p>");
                    //}

                    //this.MailService.SendMessage(model.Email, Resources.Resource.SignUpText, message.ToString());

                    // отправка письма

WayWealth/Views/Shared/Calc.cshtml
@using System.Runtime.Remoting.Messaging
@model WayWealth.Areas.lk.ViewModels.Home.InvestView
@{
    var program = ViewBag.Program as string;
    var area = ViewContext.RouteData.DataTokens["area"];
}
<script type="text/javascript">
    CP = {};
    function calc() {

        $('#sum1').val('');
        $('#sum2').val('');

        var s = $('#Sum').val() * 1;
        var sum1 = Math.floor(s * CP.percent);
        var sum2 = Math.floor(s + sum1);


        $('#sum1').text('$ ' + sum1);
        $('#sum1').attr("data-text", '$ ' + sum1);
        $('#sum2').text('$ ' + sum2);
        $('#sum2').attr("data-text", '$ ' + sum2);
    }
</script>

<div class="btn-block">
    <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="#calc-content"
       href="@Url.Action("calc", "home", new {program = "camulative", area=""})" class="camulative @(program.Equals("camulative", StringComparison.OrdinalIgnoreCase) ? "active" : "")">Camulative</a>
    <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="#calc-content"
       href="@Url.Action("calc", "home", new {program = "base", area=""})" class="@(program.Equals("base", StringComparison.OrdinalIgnoreCase) ? "active" : "")">Base</a>
    <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="#calc-content"
       href="@Url.Action("calc", "home", new {program = "optimal", area=""})" class="@(program.Equals("optimal", StringComparison.OrdinalIgnoreCase) ? "active" : "")">Optimal</a>
    <a data-ajax="true" data-ajax-mode="replace" data-ajax-update="#calc-content"
       href="@Url.Action("calc", "home", new {program = "profi", area=""})" class="@(program.Equals("profi", StringComparison.OrdinalIgnoreCase) ? "active" : "")">Profi</a>
</div>

@using (Html.BeginForm("invest", "home", new { program = program, area = "lk" }, FormMethod.Post))
{
    if (program.Equals("base", StringComparison.OrdinalIgnoreCase))
    {
        <div class="amount-block">
            <p class="subtitle">@Resources.Resource.InvestAmount</p>
            <div id="amount-range-base" class="amount-pips"></div>
            @*<div class="select-range">
                    <img src="~/Areas/lk/Content/img/amount-range-icon2.png" alt="">
                    <select id="slimSelect">
                        @for (int i = 1000; i < 5000;)
                        {
                            <option value="@i">@i</option>
                            i = i + 500;
                        }
                    </select>
                </div>*@
        </div>
        <script>
            $("#amount-range-base").slider({
                min: 1000,
                max: 4500,
                step: 500,
                value: @(Model!=null && Model.Sum > 0 ? Model.Sum : 1000),
                create: function (event, ui) {
                    var v = $(this).slider('value');
                    setTimeout(function () {
                        $('#Sum').val(v);
                        calc();
                    }, 50);
                },
                slide: function (event, ui) {
                    setTimeout(function () {
                        $('#Sum').val(ui.value);
                        calc();
                    }, 50);
                },
                change: function (event, ui) {
                    setTimeout(function () {
                        $('#Sum').val(ui.value);
                        calc();
                    }, 50);
                }
            }).slider("pips");
            //var mySelect = new SlimSelect({
            //    select: '#slimSelect',
            //    showSearch: false,
            //    onChange: (info) => {
            //        $('#Sum').val(info.value);
            //    }
            //});
        </script>
        <script>
            CP.min = 1000;
            CP.max = 4500;
            CP.step = 500;
            CP.percent = 0.3;
        </script>
    }
    if (program.Equals("optimal", StringComparison.OrdinalIgnoreCase))
    {
        <div class="amount-block">
            <p class="subtitle">@Resources.Resource.InvestAmount</p>
            <div id="amount-range-optimal" class="amount-pips"></div>
            @*<div class="select-range">
                    <img src="~/Areas/lk/Content/img/amount-range-icon2.png" alt="">
                    <select id="slimSelect">
                        @for (int i = 5000; i < 10000;)
                        {
                            <option value="@i">@i</option>
                            i = i + 500;
                        }
                    </select>
                </div>*@
        </div>
        <script>
            $("#amount-range-optimal").slider({
                min: 5000,
                max: 9500,
                step: 500,
                value: @(Model != null && Model.Sum > 0 ? Model.Sum : 5000),
                create: function (event, ui) {
                    var v = $(this).slider('value');
                    setTimeout(function () {
                        $('#Sum').val(v);
                        calc();
                    }, 50);
                },
                slide: function (event, ui) {
                    setTimeout(function () {
                        $('#Sum').val(ui.value);
                        calc();
                    }, 50);
                },
                change: function (event, ui) {
                    setTimeout(function () {
                        $('#Sum').val(ui.value);
                        calc();
                    }, 50);
                }
            }).slider("pips");
            //var mySelect = new SlimSelect({
            //    select: '#slimSelect',
            //    showSearch: false
            //});
        </script>
        <script>
            CP.min = 5000;
            CP.max = 9500;
            CP.step = 500;
            CP.percent = 0.42;
        </script>
    }
    if (program.Equals("profi", StringComparison.OrdinalIgnoreCase))
    {
        <div class="amount-block">
            <p class="subtitle">@Resources.Resource.InvestAmount</p>
            <div id="amount-range-profi" class="amount-pips"></div>
            @*<div class="select-range">
                    <img src="~/Areas/lk/Content/img/amount-range-icon2.png" alt="">
                    <select id="slimSelect">
                        @for (int i = 10000; i <= 100000;)
                        {
                            <option value="@i">@i</option>
                            i = i + 1000;
                        }
                    </select>
                </div>*@
        </div>
        <script>
            $("#amount-range-profi").slider({
                min: 10000,
                max: 100000,
                step: 10000,
                value: @(Model != null && Model.Sum > 0 ? Model.Sum : 10000),
                create: function (event, ui) {
                    var v = $(this).slider('value');
                    setTimeout(function () {
                        $('#Sum').val(v);
                        calc();
                    }, 50);
                },
                slide: function (event, ui) {
                    setTimeout(function () {
                        $('#Sum').val(ui.value);
                        calc();
                    }, 50);
                },
                change: function (event, ui) {
                    setTimeout(function () {
                        $('#Sum').val(ui.value);
                        calc();
                    }, 50);
                }
            }).slider("pips");
            //var mySelect = new SlimSelect({
            //    select: '#slimSelect',
            //    showSearch: false
            //});
        </script>
        <script>
            CP.min = 10000;
            CP.max = 100000;
            CP.step = 1000;
            CP.percent = 0.48;
        </script>
    }


    if (!program.Equals("camulative", StringComparison.OrdinalIgnoreCase))
    {
        <div class="year-block">
            <p class="lbl">@Resources.Resource.InvestAmount</p>
            <div class="input input-range">
                @Html.TextBoxFor(x => x.Sum, new { type = "number", min = "0", id = "Sum",
                    onkeypress = "return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57"
                })

            </div>
            <script type="text/javascript">
                $('#Sum').on('input change paste', calc);
            </script>
            @*<div id="year-pips" class="year-pips"></div>
                <script>
                    var yearLbl = ["<span data-text='@Resources.Resource.Year1'>@Resources.Resource.Year1</span>", "<span data-text='@Resources.Resource.Year2'>@Resources.Resource.Year2</span>", "<span data-text='@Resources.Resource.Year3'>@Resources.Resource.Year3</span>"];
                    $("#year-pips").slider({
                        min: 1,
                        max: 3,
                        step: 1,
                        value: 1
                    }).slider("pips", { rest: "label", labels: yearLbl });
                </script>*@
            <div class="total-block">
                <p>
                    @Resources.Resource.AmountProgram
                    <b id="sum1">$ 0</b>
                </p>
                <p>
                    @Resources.Resource.IncomeContribution
                    <b id="sum2">$ 0</b>
                </p>
            </div>
        </div>

        if (area == "lk")
        {
            <div class="avtoprodleniye">
                <div class="checkbox">
                    @Html.CheckBoxFor(x => x.IsProlonged)
                    @Html.LabelFor(x => x.IsProlonged, @Resources.Resource.AutoRenewal, new { title = @Resources.Resource.AutoRenewalTitle })
                    <div class="check"></div>
                </div>
            </div>
        }

        if (ViewBag.IsAllowCreateNewPlace)
        {
            <div class="avtoprodleniye">
                <div class="checkbox">
                    @Html.CheckBoxFor(x => x.IsCreateNewPlace)
                    @Html.LabelFor(x => x.IsCreateNewPlace, @Resources.Resource.CreateNewPlace)
                    <div class="check"></div>
                </div>
            </div>
        }
    }
    if (program.Equals("camulative", StringComparison.OrdinalIgnoreCase))
    {
        <div class="camulative-block">
            @Html.HiddenFor(x => x.Sum, new { Value = "300" })
            <div class="total-block">
                <p>
                    @Resources.Resource.AmountProgram
                    <b>$ 300</b>
                </p>
                <p>
                    @Resources.Resource.IncomeContribution
                    <b>$ 3 100</b>
                </p>
            </div>
        </div>
    }
    <div class="text-center">
        <a onclick="$(this).closest('form').submit()" class="btn btn-grad btn-lg">@Resources.Resource.BecomePartner</a>
    </div>
}

WayWealth/Views/Shared/_BaseLayout.cshtml
@using Common.Web
@{
    var action = ViewContext.RouteData.Values["action"].ToString();
    List<Notification> notifications = (List<Notification>)Session[Notification.Key] ?? new List<Notification>();
}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title - Way To Wealth</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/ionicons.css?v=@ViewBag.Version">
    @RenderSection("HeadSection")
</head>
<body>
    @RenderBody()
    @RenderSection("FootSection")
</body>
</html>

WayWealth/Views/Shared/_Footer.cshtml
@{ 
var culture = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
}
<footer>
    <a class="scroll_up"><i class="ion ion-ios-arrow-up"></i></a>
    <div class="container">
        <ul class="menu">
            <li>
                <a href="@Url.Action("about", "home", new { area = "" })">@Resources.Resource.menu_about</a>
            </li>
            <li>
                <a href="@Url.Action("investments", "home", new { area = "" })">@Resources.Resource.menu_invest</a>
            </li>
            <li>
                <a href="@Url.Action("partnership", "home", new { area = "" })">@Resources.Resource.menu_partnership</a>
            </li>
            <li>
                <a href="@Url.Action("news", "home", new { area = "" })">@Resources.Resource.menu_news</a>
            </li>
            @*<li>
            <a href="@Url.Action("reviews", "home", new { area = "" })">@Resources.Resource.menu_reviews</a>
        </li>*@
            <li>
                <a href="@Url.Action("faq", "home", new { area = "" })">@Resources.Resource.menu_faq</a>
            </li>
        </ul>
        <div class="flex">
            <div>
                <a href="/" class="logo">
                    <img src="~/Content/img/footer-logo-2.png" alt="">
                </a>
                <p class="text">@Resources.Resource.footer_slogan1</p>
                <div class="secure">
                    <img src="~/Content/img/use.png" alt="">
                    <div class="foot-conf">
                        @if (culture == "ru-RU")
                        {
                            <a href="~/Content/Пользовательское соглашение.pdf" target="blank">
                                @Resources.Resource.TermsUse
                            </a>
                            <a href="~/Content/Политика конфиденциальности.pdf" target="blank">
                                @Resources.Resource.PrivacyPolicy
                            </a>
                        }
                        else
                        {
                            <a href="~/Content/User agreement.pdf" target="blank">
                                @Resources.Resource.TermsUse
                            </a>
                            <a href="~/Content/Privacy policy.pdf" target="blank">
                                @Resources.Resource.PrivacyPolicy
                            </a>
                        }
                    </div>
                </div>
                <p class="text">@Resources.Resource.footer_slogan2</p>
                <ul class="crypto">
                    <li>
                        <img src="~/Content/img/1.png" alt="">
                    </li>
                    <li>
                        <img src="~/Content/img/2.png" alt="">
                    </li>
                    <li>
                        <img src="~/Content/img/3.png" alt="">
                    </li>
                    <li>
                        <img src="~/Content/img/4.png" alt="">
                    </li>
                    <li>
                        <img src="~/Content/img/5.png" alt="">
                    </li>
                </ul>
            </div>
            <div>
                <!--<ul class="soc">
                    <li>
                        <a>
                            <i class="ion ion-logo-vk"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="ion ion-logo-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="ion ion-logo-instagram"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="ion ion-logo-youtube"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <img src="~/Content/img/telegram-logo.png" alt="">
                        </a>
                    </li>
                </ul>-->
                <p class="text">@Resources.Resource.footer_slogan3</p>
                <p class="text white">@Resources.Resource.footer_slogan4</p>
                <a href="mailto:info@w2w.fund" class="email">
                    <i class="ion ion-ios-mail"></i>info@w2w.fund
                </a>
                <p class="text">
                    <span>©</span> @Resources.Resource.Copyright
                </p>
            </div>
        </div>
    </div>
    
</footer>

WayWealth/Views/Shared/_Header.cshtml
@{ 
    var culture = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
}
<header>
    <div class="top-block">
        <a href="/" class="logo">
            <img src="~/Content/img/logo-2.png" alt="">
        </a>
        <ul class="menu">
            <li class="">
                <a href="@Url.Action("about", "home", new { area="" })" data-text="@Resources.Resource.menu_about">@Resources.Resource.menu_about</a>
            </li>
            <li>
                <a href="@Url.Action("investments", "home", new { area="" })" data-text="@Resources.Resource.menu_invest">@Resources.Resource.menu_invest</a>
            </li>
            <li>
                <a href="@Url.Action("partnership", "home", new { area="" })" data-text="@Resources.Resource.menu_partnership">@Resources.Resource.menu_partnership</a>
            </li>
            <li>
                <a href="@Url.Action("news", "home", new { area="" })" data-text="@Resources.Resource.menu_news">@Resources.Resource.menu_news</a>
            </li>
            @*<li>
            <a href="@Url.Action("reviews", "home", new { area="" })" data-text="@Resources.Resource.menu_reviews">@Resources.Resource.menu_reviews</a>
        </li>*@
            <li>
                <a href="@Url.Action("faq", "home", new { area="" })" data-text="@Resources.Resource.menu_faq">@Resources.Resource.menu_faq</a>
            </li>
        </ul>
        <div class="lk-lang-block">
            @Html.Action("UserInfo", "home", new { area = "" })
            <div class="lang">
                @if (culture == "ru-RU")
                {
                    <a class="active">
                        <img src="~/Content/img/ru.png" alt="">
                        <span>RU</span>
                    </a>
                    <a href="@Url.Action("ChangeCulture", "home", new { lang = "en", area="" })">
                        <img src="~/Content/img/en.png" alt="">
                        <span>EN</span>
                    </a>
                }
                else
                {
                    <a class="active">
                        <img src="~/Content/img/en.png" alt="">
                        <span>EN</span>
                    </a>
                    <a href="@Url.Action("ChangeCulture", "home" , new { lang = "ru", area="" })">
                        <img src="~/Content/img/ru.png" alt="">
                        <span>RU</span>
                    </a>
                }
            </div>
        </div>
        <a class="menu-btn">
            <i class="icon ion-md-menu"></i>
            <i class="icon ion-md-close"></i>
        </a>
    </div>
    <div class="m-top-block top-block">
        <div class="lk-lang-block">
            @Html.Action("UserInfo", "home", new { area = "" })
        </div>
    </div>
    @Html.Action("UserBalances", "home", new { area = "" })
</header>

WayWealth/Views/Shared/_UserBalances.cshtml
@model WayWealth.Infrastructure.Auth.CustomPrincipal

<div class="bottom-block">
    <div class="flex">
        <i>@Resources.Resource.AccountBalances</i>
        <p>
            <span>@Resources.Resource.Facial.ToLower()</span>
            <b>$ @(Model.BalanceInner.ToString("N2")) </b>
        </p>
        <p>
            <span>@Resources.Resource.Investment.ToLower()</span>
            <b>$ @(Model.BalanceInvestments.ToString("N2"))</b>
        </p>
        <p>
            <span>@Resources.Resource.Percent.ToLower()</span>
            <b>$ @(Model.BalancePercents.ToString("N2"))</b>
        </p>
        <p>
            <span>@Resources.Resource.Rewards.ToLower()</span>
            <b>$ @(Model.BalanceRewards.ToString("N2"))</b>
        </p>
    </div>
</div>

WayWealth/Views/Shared/_UserInfoAuth.cshtml
@model WayWealth.Infrastructure.Auth.CustomPrincipal

<a class="signOut" href="@Url.Action("Out", "Sign", new { area=""})">
    @Resources.Resource.menu_out
</a>
<a class="lkName" href="@Url.Action("index", "home", new { area = "lk" })">
    <span>@Resources.Resource.menu_kabinet</span>
    <p>
        @Model.FirstName @(!string.IsNullOrWhiteSpace(Model.LastName) ? Model.LastName.Substring(0, 1) : string.Empty)
        @(!string.IsNullOrWhiteSpace(Model.MiddleName) ? Model.MiddleName.Substring(0, 1) : string.Empty)
    </p>
</a>

WayWealth/Views/Shared/_UserInfoNotAuth.cshtml
<a href="@Url.Action("in", "sign")" class="signIn">
    @Resources.Resource.menu_in
</a>
<a href="@Url.Action("up", "sign")" class="signIn signReg">
    @Resources.Resource.menu_up
</a>